start = Time.now
puts 'Cleaning database...'
Trip.destroy_all
User.destroy_all
Activity.destroy_all

puts 'Creating users...'
alexia = User.create!(first_name: "Alexia", last_name: "Le Tarnec", email: "alexia@gmail.com", password: "azertyuiop")
guillaume = User.create!(first_name: "Guillaume", last_name: "Hercot", email: "guillaume@gmail.com", password: "azertyuiop")
julie = User.create!(first_name: "Julie", last_name: "Simon", email: "julie@gmail.com", password: "azertyuiop")
mathilde = User.create!(first_name: "Mathilde", last_name: "Ganancia", email: "mathilde@gmail.com", password: "azertyuiop")
hector = User.create!(first_name: "Hector", last_name: "Louvot", email: "hector@gmail.com", password: "azertyuiop")

julie.remote_photo_url = "https://kitt.lewagon.com/placeholder/users/juliesimon"
julie.save!
hector.remote_photo_url = "https://img.discogs.com/a7l_WU-z26_uKxy2bsz_-Um4NQU=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/A-38204-1498364732-2978.jpeg.jpg"
hector.save!

puts 'Creating activities...'
activities_attributes = [

  {
    title:" Exhibition Sophie Calle : beau doublé monsieur le Marquis",
    name: "Musée de la Chasse et de la Nature",
    address: "62 rue des Archives 75003 Paris",
    photo:"https://media.timeout.com/images/104623692/750/422/image.jpg",
    family: true,
    couple: true,
    friends: true,
    solo: true,
    budget: 3,
    knows_the_city: 3,
    art_lover: true,
    to_book: false,
    website: "http://www.chassenature.org/sophie-calle-et-son-invitee-serena-carone/",
  },
  {
    title:" Exhibition Women House",
    name: "Monnaie de Paris",
    address: "11 quai de Conti 75006 Paris",
    photo:"https://media.timeout.com/images/104673306/750/422/image.jpg",
    family: true,
    couple: true,
    friends: true,
    solo: true,
    budget: 3,
    knows_the_city: 3,
    art_lover: true,
    to_book: false,
    website: "https://www.google.fr/search?q=women+house+monnaie+de+paris&oq=women+house+monair&aqs=chrome.1.69i57j0.5934j0j4&sourceid=chrome&ie=UTF-8",
  },
  {
    title:" Exhibition Clément Cogitore",
    name: "Le Bal",
    address: "6 impasse de la Défense 75018 Paris",
    photo:"https://media.timeout.com/images/104093092/750/422/image.jpg",
    family: true,
    couple: true,
    friends: true,
    solo: true,
    budget: 3,
    knows_the_city: 3,
    art_lover: true,
    to_book: false,
    website: "http://www.le-bal.fr/2017/06/clement-cogitore",
  },
  {
    title:"Exhibition Malick Sidibé : Mali Twist",
    name: "Fondation Cartier",
    address: "261 boulevard Raspail 75014 Paris",
    photo:"https://media.timeout.com/images/104097644/750/422/image.jpg",
    family: true,
    couple: true,
    friends: true,
    solo: true,
    budget: 3,
    knows_the_city: 3,
    art_lover: true,
    to_book: false,
    website: "https://www.fondationcartier.com/#/fr/art-contemporain/55/editions/289/toutes-les-publications/348/malick-sidibe-bamako-1962-1976/",
  },
  {
    title:"Barbara exhibition",
    name: "Philarmonie de Paris",
    address: "221 avenue Jean Jaurès 75019 Paris",
    photo:"https://media.timeout.com/images/104088792/710/399/image.jpg",
    family: true,
    couple: true,
    friends: true,
    solo: true,
    budget: 2,
    knows_the_city: 3,
    art_lover: true,
    to_book: false,
    website: "https://philharmoniedeparis.fr/fr/exposition-barbara",
  },
  {
    title:"Galerie d'art contemporain",
    name: "Galerie Thaddaeus Ropac",
    address: "7 rue Debelleyme",
    photo:"https://media.timeout.com/images/100017453/710/399/image.jpg",
    family: true,
    couple: true,
    friends: true,
    solo: true,
    budget: 3,
    knows_the_city: 3,
    art_lover: true,
    to_book: false,
    website: "http://ropac.net/",
  },
  {
    title:"Pierre Paulin – Boom boom, run run Exhibition",
    name: "Le Plateau - FRAC",
    address: "22 rue des Alouettes 75019 Paris",
    photo:"https://www.fraciledefrance.com/wp/wp-content/uploads/Boom-boom-run-run-site2-1024x724.jpg",
    family: true,
    couple: true,
    friends: true,
    solo: true,
    budget: 3,
    knows_the_city: 3,
    art_lover: true,
    to_book: false,
    website: "https://www.fraciledefrance.com/pierre-paulin-boom-boom-run-run/",
  },
  {
    title:"Caro/Jeunet Exhibition",
    name: "Halle Saint Pierre",
    address: "2 rue Ronsard 75018 Paris",
    photo:"https://media.timeout.com/images/103970015/750/422/image.jpg",
    family: true,
    couple: true,
    friends: true,
    solo: true,
    budget: 3,
    knows_the_city: 3,
    art_lover: true,
    to_book: false,
    website: "http://www.hallesaintpierre.org/2017/06/27/caro-jeunet/",
  },
  {
    title:"Walk at the parc des Buttes-Chaumont",
    name: "Buttes-Chaumont",
    address: "1 Rue Botzaris, 75019 Paris",
    photo:"http://www.unjourdeplusaparis.com/files/2016/05/balade-parc-buttes-chaumont.jpg",
    family: true,
    couple: true,
    friends: true,
    solo: true,
    nature_lover: true,
    to_book: false,
    budget: 3,
    knows_the_city: 3,
  },

  {
    title:"Walk around the Butte Bergeyre",
    name: "Butte Bergeyre",
    address: "76 Rue Georges Lardennois, 75019 Paris",
    photo:"https://3.bp.blogspot.com/-3RT2VoG97B8/VLqoHdOBT9I/AAAAAAAAXfc/M9L8t2LE98A/s1600/butte%2Bbergeyre%2Bparis%2B19%2B16%2Bbis.JPG",
    family: true,
    couple: true,
    friends: true,
    solo: true,
    city_wanderer: true,
    nature_lover: true,
    to_book: false,
    budget: 3,
    knows_the_city: 3,
  },
  {
    title:"Stroll at the canal de l'Ourcq",
    name: "Canal de l'Ourcq",
    address: "26-28 Quai de la Marne, 75019 Paris",
    photo:"https://upload.wikimedia.org/wikipedia/commons/3/33/Canal_Saint_Martin_vu_de_vers_la_Rotonde_de_la_Villette.jpg",
    family: true,
    couple: true,
    friends: true,
    solo: true,
    city_wanderer: true,
    to_book: true,
    budget: 3,
    knows_the_city: 3,
  },
  {
    title:"Break session at les Bains d'Orient",
    name: "Les Bains d'Orient",
    address: "7 Place de la Bataille de Stalingrad, 75010 Paris",
    photo:"http://www.riadsmorocco.com/photos/riad-jnane-sherazade-hammam.jpg",
    couple: true,
    solo: true,
    relaxed: true,
    to_book: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://www.lesbainsdorient.com/",
  },
  {
    title:"Break session at the Hammam du canal",
    name: "Hammam du canal",
    address: "156 Rue de Crimée, 75019 Paris",
    photo:"https://www.piscines-de-france.fr/images/pages/galerie46/hammam-carrele.jpg",
    couple: true,
    solo: true,
    relaxed: true,
    to_book: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://www.hammam-du-canal.com/",
  },
  {
    title:"Visit of the Saint-Serge church",
    name: "Eglise Orthodoxe Saint-Serge",
    address: "93 Rue de Crimée, 75019 Paris",
    photo:"http://www.unjourdeplusaparis.com/files/2012/07/visite-saint-serge-radonege-paris.jpg",
    couple: true,
    solo: true,
    family: true,
    friends: true,
    history_passionate: true,
    to_book: true,
    city_wanderer: true,
    sight_seeing_adventurer: true,
    knows_the_city: 3,
  },

    {
    title:"Swimming break at the club Papillon",
    name: "Espace Sportif Pailleron",
    address: "32 Rue Edouard Pailleron, 75019 Paris",
    photo:"http://www.linternaute.com/paris/magazine/diaporama/06/piscine-patinoire-pailleron/images/complexe-sportif-pailleron-1.jpg",
    couple: true,
    solo: true,
    family: true,
    friends: true,
    to_book: true,
    sport_lover:true,
    budget: 3,
    knows_the_city: 3,
    website: "http://www.pailleron19.com/",
  },

  {
    title:"Thaï Boxe session",
    name: "ASMBF",
    address: "5 Rue des Lilas, 75019 Paris",
    photo:"http://www1.pictures.zimbio.com/gi/Floyd+Mayweather+Jr+v+Canelo+Alvarez+j54F35Et2Etx.jpg",
    couple: true,
    solo: true,
    family: true,
    friends: true,
    to_book: true,
    sport_lover:true,
    budget: 3,
    knows_the_city: 3,
    website: "http://www.asmbf.fr/ASMBF_Paris_Boxing_Club/Home.html",
  },

  {
    title:"Stroll at the Alsacian Christmas market",
    name: "Marché de Noël",
    address: "Gare de l'Est, 75010 Paris",
    photo:"http://medias.tourism-system.com/7/4/307599_13196-marche_noel_87186.jpg",
    couple: true,
    solo: true,
    family: true,
    friends: true,
    to_book: false,
    food_addict: true,
    city_wanderer: true,
    budget: 3,
    knows_the_city: 3,
  },

  {
    title:"Discovery of Argentin Tango",
    name: "La Casa del Tango",
    address: "11 Allée Darius Milhaud, 75019 Paris",
    photo:"https://tango-attitude.com/wp-content/uploads/2015/09/cours-tango-strasbourg.png",
    couple: true,
    solo: true,
    family: true,
    friends: true,
    to_book: true,
    sport_lover:true,
    budget: 3,
    knows_the_city: 3,
    website: "http://www.lacasadeltango.net/",
  },

  {
    title:"Pilates session",
    name: "NEDJMA - École de danse",
    address: "41 Rue des Solitaires, 75019 Paris",
    photo:"http://www.kio-o.ca/wp-content/uploads/2016/05/fotolia_74609218.jpg",
    solo: true,
    friends: true,
    to_book: true,
    sport_lover:true,
    budget: 3,
    knows_the_city: 3,
    website: "http://www.nedjmadanse.com/ecole.htm",
  },
  {
    title:"Danse class at Studio Nilanthi",
    name: "Studio Nilanthi",
    address: "83 Rue Rebeval, 75019 Paris",
    photo:"https://studio-nilanthi.com/images/home-slide-1.jpg?crc=9313831",
    solo: true,
    friends: true,
    to_book: true,
    sport_lover:true,
    budget: 3,
    knows_the_city: 3,
    website: "http://www.http://studio-nilanthi.com/",
  },
  {
    title:"Meditation break",
    name: "Dojo Zen Paris",
    address: "210 Rue de Belleville, 75020 Paris",
    photo:"http://img.over-blog-kiwi.com/0/83/70/99/20150408/ob_1d8c39_img-3796.JPG",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    relaxed: true,
    budget: 3,
    knows_the_city: 3,
    website: "www.dojozenparis.com/",
  },
    {
    title:"Rowing session at the canal La Villette",
    name: "Base nautique de la Villette",
    address: "17 Quai de la Loire, 75019 Paris",
    photo:"https://www.momondo.fr/inspiration/wp-content/uploads/sites/11/2017/08/activites-sportives-paris-aviron-istock-low-reso.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: true,
    sport_lover: true,
    budget: 1,
    knows_the_city: 3,
    website: "https://www.paris.fr/services-et-infos-pratiques/sports-et-loisirs/ou-faire-du-sport/le-sport-en-plein-air-2016#les-bases-nautiques_6",
  },
    {
    title:"Shopping at the Galeries Lafayette",
    name: "Galeries Lafayette",
    address: "40 boulevard Haussmann, 75009 Paris",
    photo:"http://be.france.fr/sites/default/files/coupole_galeries_lafayette_paris_haussmanncgaleries_lafayette_paris_haussmann.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    serial_shopper: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://haussmann.galerieslafayette.com/",
  },
    {
    title:"Shopping at the Bon Marché",
    name: "Bon Marché - Rive Gauche",
    address: "24 rue de Sevres, 75007 Paris",
    photo:"https://r.lvmh-static.com/uploads/2014/10/lbm_cover-2800x1312-2800x1312.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    serial_shopper: true,
    budget: 5,
    knows_the_city: 3,
    website: "https://www.24sevres.com/fr-fr/le-bon-marche",
  },
      {
    title:"La Mercerie Parisienne in the Marais neighborhood",
    name: "La Mercerie Parisienne",
    address: "8 rue des Francs-Bourgeois, 75003 Paris",
    photo:"https://uploads.lebonbon.fr/source/2017/paris/mai/site/merceriecouv.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    serial_shopper: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://www.lamercerieparisienne.com/fr/",
  },
        {
    title:"Decoration at the Marché aux Puces",
    name: "Le Marché aux Puces de Saint Ouen",
    address: "124 rue des rosiers, 93400 Saint Ouen",
    photo:"https://www.parisianist.com/assets/img/articles/saint_ouen_flea_market/en/saint-ouen-flea-market-13.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    serial_shopper: true,
    budget: 2,
    knows_the_city: 3,
    website: "http://www.marcheauxpuces-saintouen.com/1.aspx",
  },
          {
    title:"Shopping at the heart of Paris",
    name: "Galerie Vivienne",
    address: "6 rue Vivienne, 75002 Paris",
    photo:"http://www.galerie-vivienne.com/public/1164/contenu/1(1).jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    serial_shopper: true,
    budget: 3,
    knows_the_city: 4,
    website: "http://www.galerie-vivienne.com/",
  },
            {
    title:"Affordable Shopping session",
    name: "Vestiboutique Croix-rouge Paris 4",
    address: "36 rue Geoffroy-l'Asnier, 75004 Paris",
    photo:"https://uploads.lebonbon.fr/source/2017/paris/site/aout/Sans_titre-1_2.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    serial_shopper: true,
    budget: 1,
    knows_the_city: 3,
    website: "http://paris.croix-rouge.fr/cat/vestiboutique/",
  },
              {
    title:"Vintage shopping at le Marais",
    name: "Au comptoir du chineur",
    address: "49 rue Saint Paul, 75004 Paris",
    photo:"https://media.timeout.com/images/103488973/1372/772/image.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    serial_shopper: true,
    budget: 2,
    knows_the_city: 3,
    website: "https://www.facebook.com/comptoirsduchineur",
  },
                {
    title:"Interior design shopping at Pigalle",
    name: "The Cool Republic",
    address: "72 rue des Martyrs, 75009 Paris",
    photo:"https://media.timeout.com/images/103646712/1372/772/image.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    serial_shopper: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://www.thecoolrepublic.com/",
  },
                  {
    title:"Jewellery shopping at l'Atelier Haut Perché",
    name: "L'Atelier Haut Perché",
    address: "29 rue des dames, 75017 Paris",
    photo:"https://media.timeout.com/images/103240302/1372/772/image.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    serial_shopper: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://www.atelierhautperche.com/showcase/free-move/",
  },
                    {
    title:"Shopping at the well-known English Library of Paris",
    name: "Shakespeare & Company",
    address: "37 rue de la Bûcherie, 75005 Paris",
    photo:"https://media.timeout.com/images/100007243/1372/772/image.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    serial_shopper: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://shakespeareandcompany.com/",
  },
                      {
    title:" Christmas Rink on the Grande Arche rooftop",
    name: "Patinoire de Noël",
    address: "Grande Arche de la Défense - 92044 Paris La Défense",
    photo:"http://lacritique.fr/wp-content/uploads/2017/11/870x489_dpacreative044081-750x489.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: true,
    sport_lover: true,
    budget: 2,
    knows_the_city: 3,
    website: "https://www.parisinfo.com/sortie-paris/182108/patinoire-haut-grande-arche",
  },
                        {
    title:"Free Swedish gym session",
    name: "Gym Suédoise",
    address: "4-12 rue Dénoyez, 75020 Paris",
    photo:"http://static.by-night.fr/uploads/documents/58c/139/93d/58c13993d0a59.jpg?v1.0",
    solo: true,
    couple: true,
    friends: true,
    to_book: true,
    sport_lover: true,
    budget: 1,
    knows_the_city: 3,
    website: "https://www.gymsuedoise.com/loc/dt/?id=66",
  },
                          {
    title:"Keller Swimming Pool",
    name: "Piscine Keller",
    address: "14 rue de l'Ingénieur Robert Keller, 75015 Paris",
    photo:"http://www.pariszigzag.fr/wp-content/uploads/2013/09/piscine-plein-air-paris.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: true,
    sport_lover: true,
    budget: 2,
    knows_the_city: 3,
    website: "https://www.parisinfo.com/musee-monument-paris/72893/Piscine-Keller",
  },
                            {
    title:"Hot Yoga Bikram session",
    name: "Yoga Bikram",
    address: "5-7 rue Meissonier, 75017 Paris",
    photo:"https://img.grouponcdn.com/deal/6fHSqfqDPHxfWWDDYuYo/3d-900x540/v1/c700x420.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: true,
    sport_lover: true,
    budget: 4,
    knows_the_city: 3,
    website: "http://www.lespacebikramparis.com/fr",
  },
                              {
    title:"Gym session in a wooden complex",
    name: "Centre Sportif Suchet",
    address: "25 avenue du marechal franchet d'esperey, 75016 Paris",
    photo:"https://api-site-cdn.paris.fr/images/85655?w=Large",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    sport_lover: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://escalade.paris.fr/",
  },
                                {
    title:"Climbing session",
    name: "Paris Escalade",
    address: "37 route des Petits Ponts, 75019 Paris",
    photo:"http://www.blocbuster.fr/wp-content/uploads/2011/12/blocbuster-escalade-paris-la-defense-1-1170x779.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: true,
    sport_lover: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://escalade.paris.fr/",
  },
                                  {
    title:"Diving session",
    name: "Club de Plongée du Vème",
    address: "4 rue des Arènes, 75005 Paris",
    photo:"https://www.plongequilibre.com/s/cc_images/teaserbox_7185729.jpg?t=1494056767",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    sport_lover: true,
    budget: 3,
    knows_the_city: 3,
    website: "http://www.clubdeplongeedu5.org/",
  },
                                  {
    title:"Futsal class",
    name: "Le Five Paris",
    address: "32 Rue Moussorgski, 75018 Paris",
    photo:"https://parisiandays.files.wordpress.com/2012/09/capture-d_c3a9cran-2012-09-27-c3a0-12-21-04.png",
    solo: true,
    couple: true,
    friends: true,
    to_book: true,
    sport_lover: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://www.lefive.fr/",
  },
                                    {
    title:"Zumba class to let off steam",
    name: "Zumba Paris",
    address: "31 rue Chapon, 75003 Paris",
    photo:"https://www.cmgsportsclub.com/sites/default/files/styles/visuel-980w/public/activity/zumba.jpg?itok=pipvc_4p",
    solo: true,
    couple: true,
    friends: true,
    to_book: true,
    sport_lover: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://www.zumbasite.com/",
  },
                                      {
    title:"Riding classes at la Villette",
    name: "Centre équestre de la Villette",
    address: "9 Boulevard Macdonald, 75019 Paris",
    photo:"http://www.equivil.fr/img/bandeau/lav.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: true,
    sport_lover: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://www.facebook.com/Lavillette.equivil/?fref=ts",
  },
                                     {
    title:"Most indecent snack of Paris",
    name: "Tea Time de la sorcière - Hotel Hyatt",
    address: "24 boulevard Melesherbes, 75008 Paris",
    photo:"https://uploads.lebonbon.fr/source/2017/paris/hyattcouv.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    food_addict: true,
    budget: 2,
    knows_the_city: 3,
    website: "https://parismadeleine.hyatthotels.hyatt.com/fr/hotel/activities/hotel-activities/vos-fetes-de-fin-d-annee-au-hyatt-paris-madeleine.html",
  },
   {
    title:"Most excentric burgers of Paris",
    name: "B-Boyzs Burger",
    address: "5 avenue Trudaine, 75009 Paris",
    photo:"https://uploads.lebonbon.fr/source/2017/paris/novembre/bboyz/bboyz950.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    food_addict: true,
    budget: 2,
    knows_the_city: 3,
    website: "http://www.bboyz.fr/",
  },
    {
    title:"Gourmet break: the best fromagerie of Paris",
    name: "Le Claque-Fromage",
    address: "49 avenue Trudaine, 75009 Paris",
    photo:"https://uploads.lebonbon.fr/source/2017/paris/site/avril/mises_en_ligne/claquefromage04.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    food_addict: true,
    budget: 2,
    knows_the_city: 3,
    website: "https://www.facebook.com/LeClaqueFromage/?fref=ts",
  },
    {
    title:"Discovery of a chocolat shop and tea place",
    name: "La Mutinerie",
    address: "15 rue Henry-Monnier, 75009 Paris",
    photo:"http://www.chocolaterielamutinerie.com/wp-content/uploads/2017/08/04.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    food_addict: true,
    budget: 3,
    knows_the_city: 3,
    website: "http://www.chocolaterielamutinerie.com/",
  },
    {
    title:"Lebanese restaurant full of taste",
    name: "Zoé à Beyrouth",
    address: "42 rue des Acacias, 75017 Paris",
    photo:"https://uploads.lebonbon.fr/source/2017/paris/site/novembre/mises_en_ligne/ZoeI_1.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    food_addict: true,
    budget: 3,
    knows_the_city: 3,
    website: "https://www.zoeabeyrouth.com/",
  },
   {
    title:"Great Seafood Bar in the 11th district",
    name: "Bar à Iode",
    address: "18 rue Jean Macé, 75011 Paris",
    photo:"http://baraiode.fr/images/bg-4.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    food_addict: true,
    budget: 4,
    knows_the_city: 3,
    website: "http://baraiode.fr/",
  },
  {
    title:"Best beef ribs in Paris",
    name: "A côté",
    address: "16 rue Lafayette, 75009 Paris",
    photo:"https://uploads.lebonbon.fr/source/2017/paris/octobre/melk/a_cote/acote950.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    food_addict: true,
    budget: 4,
    knows_the_city: 3,
    website: "https://www.acote.paris/",
  },
                                                     {
    title:"Greek Restaurant at the Puces de Saint Ouen",
    name: "Yaya Restaurant",
    address: "8 rue de l'Hippodrome, 93400 Saint-Ouen",
    photo:"http://kissmychef.com/wp-content/uploads/2017/06/yaya_restaurant-770x514.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    food_addict: true,
    budget: 4,
    knows_the_city: 3,
    website: "http://www.yayarestaurant.com/",
  },
                                                       {
    title:"Tapas Bar at Saint Germain des Près",
    name: "L'Avant Comptoir d'Yves Candeborde",
    address: "3 carrefour de l'Odeon, 75006 Paris",
    photo:"https://lefooding.com/media/W1siZiIsIjIwMTYvMDIvMDIvMTdfMTNfNTVfNDIzX3Jlc3RhdXJhbnRfbGF2YW50X2NvbXB0b2lyX3BhcmlzLmpwZyJdLFsicCIsInRodW1iIiwiNjcyeDYwMCJdXQ/restaurant-lavant-comptoir-paris.jpg?sha=f30c7894",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    food_addict: true,
    budget: 4,
    knows_the_city: 3,
    website: "https://www.facebook.com/lavantcomptoir/",
  },
                                                         {
    title:"Delicious coffee shop à Opéra",
    name: "Braun Notes Coffee",
    address: "33 rue de Mogador, 75009 Paris",
    photo:"https://uploads.lebonbon.fr/source/2017/paris/site/mai/mises_en_ligne/Braun_coffe_shop_1.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    food_addict: true,
    budget: 2,
    knows_the_city: 3,
    website: "https://www.facebook.com/braunnotescoffee/",
  },
                                                         {
    title:"Zen Nature: Jardin Japonais du Panthéon Bouddhique",
    name: "Panthéon Bouddhique",
    address: "19 avenue d'Iena, 75016 Paris",
    photo:"https://wildesk.fr/le-blog/wp-content/uploads/sites/2/2017/06/ob_9c9430_jardin-japonais-11.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    nature_lover: true,
    budget: 1,
    knows_the_city: 3,
    website: "http://www.guimet.fr/",
  },
  {
    title:"Scientific nature: Jardin Botanique de la faculté des sciences",
    name: "Jardin Botanique de la Faculté des Sciences Pharmaceutiques et Biologiques",
    address: "4 Avenue de l'Observatoire, 75006 Paris",
    photo:"https://wildesk.fr/le-blog/wp-content/uploads/sites/2/2017/06/ob_9c9430_jardin-japonais-11.jpg",
    solo: true,
    couple: true,
    friends: true,
    to_book: false,
    nature_lover: true,
    budget: 1,
    knows_the_city: 4,
    website: "http://www.pharmacie.univ-paris5.fr/spip.php?article2274",
  },
  {
    title:"Romantic stroll: Garden of the musée de la vie Romantique",
    name: "Jardin du Musée de la vie Romantique",
    address: "416 rue Chaptal, 75009 Paris",
    photo:"https://wildesk.fr/le-blog/wp-content/uploads/sites/2/2017/06/musc3a9e-vie-romantique.jpg",
    solo: true,
    couple: false,
    friends: true,
    to_book: false,
    nature_lover: true,
    budget: 1,
    knows_the_city: 2,
    website: "http://www.vie-romantique.paris.fr/fr",
  },
  {
  title:"Hidden nature at the heart of le Marais",
  name: "Jardin des Francs-bourgeois-rosiers",
  address: "35-37 rue des Francs-Bourgeois, 75004 Paris",
  photo:"https://wildesk.fr/le-blog/wp-content/uploads/sites/2/2017/06/jardin-des-rosiers-joseph-migneret-marais-paris-4.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  nature_lover: true,
  budget: 1,
  knows_the_city: 2,
  website: "http://equipement.paris.fr/jardin-des-rosiers-joseph-migneret-ex-francs-bourgeois-rosiers-2828",
},
  {
  title:"Historic nature: the oldest tree of Paris",
  name: "Square René Viviani-Montebello",
  address: "25 Quai de Montebello, 75005 Paris",
  photo:"https://wildesk.fr/le-blog/wp-content/uploads/sites/2/2017/06/leplusviel-arbre-de-paris.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  nature_lover: true,
  budget: 1,
  knows_the_city: 4,
  website: "http://equipement.paris.fr/square-rene-viviani-2441",
},
  {
  title:"Le Jardin Naturel of Paris",
  name: "Jardin naturel du 20ème arrondissement",
  address: "120 rue de la Réunion, 75020 Paris",
  photo:"http://unpetitpoissurdix.fr/wp-content/uploads/2013/11/dsc04266.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  nature_lover: true,
  budget: 1,
  knows_the_city: 4,
  website: "http://equipement.paris.fr/jardin-naturel-pierre-emmanuel-2703",
},
  {
  title:"Le Jardin Sauvage of Paris",
  name: "Jardin Sauvage, Saint-Vincent",
  address: "17 rue Saint-Vincent, 75018 Paris",
  photo:"http://www.lamaisondulysse.com/wp-content/uploads/2015/10/la-maison-d-ulysse-uzes-jardin-sauvage.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  nature_lover: true,
  budget: 1,
  knows_the_city: 4,
  website: "https://www.parisinfo.com/musee-monument-paris/72357/Jardin-sauvage-Saint-Vincent",
},
  {
  title:"Discovery of the Parc Montsouris",
  name: "Parc Montsouris",
  address: "2 rue Gazan, 75014 Paris",
  photo:"https://media-cdn.tripadvisor.com/media/photo-s/01/0c/70/33/lake-at-parc-montsouris.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  nature_lover: true,
  budget: 1,
  knows_the_city: 2,
  website: "https://www.parisinfo.com/musee-monument-paris/71218/Parc-Montsouris",
},
  {
  title:"Parc: Bois de Vincennes",
  name: "Bois de Vincennes",
  address: "route de la Pyramide, 75020 Paris",
  photo:"https://www.parisinfo.com/var/otcp/sites/images/node_43/node_51/node_230/running-au-bois-de-vincennes-630x405-c-otcp-marc-bertrand/18006742-1-fre-FR/Running-au-bois-de-Vincennes-630x405-C-OTCP-Marc-Bertrand.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  nature_lover: true,
  budget: 1,
  knows_the_city: 2,
  website: "http://equipement.paris.fr/bois-de-vincennes-6598",
},
  {
  title:"Stroll at the Jardin des Plantes",
  name: "Jardin des plantes",
  address: "57 rue Cuvier, 75005 Paris",
  photo:"http://www.jardindesplantes.net/sites/jardindesplantes/files/styles/bandeau_home/public/thumbnails/image/jerome-munier-retouche_1440_850.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  nature_lover: true,
  budget: 1,
  knows_the_city: 2,
  website: "http://www.jardindesplantes.net/",
},
{
  title:"Special Effects at La Cité des Sciences",
  name: "Cité des sciences et de l'industrie",
  address: "30 avenue Corentin-Cariou, 75019 Paris",
  photo:"http://www.cite-sciences.fr/fileadmin/fileadmin_CSI/fichiers/vous-etes/enseignant/Votre-visite/Expositions-temporaires/_images/Effets-speciaux/Affiche-effets-speciaux-2-430.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: true,
  tech_fan: true,
  budget: 3,
  knows_the_city: 3,
  website: "http://cite-sciences.fr/",
},
{
  title:"Capitaine Futur at the Gaité Lyrique",
  name: "Gaité Lyrique Paris",
  address: "3 bis rue Papin, 75003 Paris",
  photo:"https://gaite-lyrique.net/sites/default/files/styles/slider/public/capfut_web_0.jpg?itok=jJ6Buqpk",
  solo: true,
  couple: true,
  friends: true,
  to_book: true,
  tech_fan: true,
  budget: 1,
  knows_the_city: 2,
  website: "https://gaite-lyrique.net/festival/capitaine-futur",
},
{
  title:"E-lab Video Game Space",
  name: "Cité des sciences et de l'Industrie",
  address: "30 avenue Corentin-Cariou, 75019 Paris",
  photo:"http://www.cite-sciences.fr/fileadmin/_processed_/csm_jouer1_a66b76e9d2.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: true,
  tech_fan: true,
  budget: 1,
  knows_the_city: 2,
  website: "http://www.cite-sciences.fr/fr/au-programme/expos-temporaires/e-lab/",
},
{
  title:"Escape Game",
  name: "The Game",
  address: "30 avenue Corentin-Cariou, 75019 Paris",
  photo:"http://lemystere.fr/wp-content/uploads/2015/10/Escape_game_loiret_yonne_003_M.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: true,
  tech_fan: true,
  budget: 1,
  knows_the_city: 3,
  website: "https://www.thegame-france.com/",
},
{
  title:"Gaming stop at the Meltdown",
  name: "Meltdown Bar Paris",
  address: "6 Passage Thiéré, 75011 Paris",
  photo:"http://www.afjv.com/diaporama/141209-destiny/full/destiny-meltdown-119.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  tech_fan: true,
  budget: 3,
  knows_the_city: 3,
  website: "https://www.meltdown.bar/paris",
},
{
  title:"Have a drink at the Deux Point Zéro bar",
  name: "Le deux point zéro",
  address: " 7 Rue Blondel, 75003 Paris",
  photo:"https://www.france-hotel-guide.com/fr/blog/wp-content/uploads/2014/06/rsz_deux_point_zéro_facebook.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  tech_fan: true,
  budget: 3,
  knows_the_city: 4,
  website: "http://www.deuxpointzerobar.com/",
},
{
  title:"Shopping stop at the geekest concept store of Paris",
  name: "Geeks and Vape",
  address: "52 rue Basfroi, 75011 Paris",
  photo:"https://www.france-hotel-guide.com/fr/blog/wp-content/uploads/2017/04/rsz_14040091_265571950496136_1627812985565128713_n.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  tech_fan: true,
  budget: 4,
  knows_the_city: 5,
  website: "https://www.facebook.com/geeksandvape/",
},
{
  title:"Visit of the biggest startup campus of the world in Paris",
  name: "Station F",
  address: "5 parvis Alan Turing, 75013 Paris",
  photo:"https://thespaces.com/wp-content/uploads/2017/07/Station-F-Halle-Freyssinet-Paris-8.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  tech_fan: true,
  budget: 1,
  knows_the_city: 3,
  website: "https://stationf.co/fr/",
},
{
  title:"Gaming session, 'la tête dans les nuages'",
  name: "La tête dans les nuages",
  address: "5 boulevard des Italiens, 75002 Paris",
  photo:"https://www.proxifun.com/wp-content/uploads/2016/11/la-tete-dans-les-nuages-paris-1.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  tech_fan: true,
  budget: 3,
  knows_the_city: 3,
  website: "http://www.ltdn.com/fr/",
},
{
  title:"The Big Wheel of Paris",
  name: "The Big Wheel - place de la Concorde",
  address: "Place de la Concorde, 75008 Paris",
  photo:"http://img.bfmtv.com/c/1256/708/a9f/f32fa8b50f5470ad041528b792c9c.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  sight_seeing_adventurer: true,
  budget: 3,
  knows_the_city: 2,
  website: "http://www.ltdn.com/fr/",
},
{
  title:"Visit of the Panthéon in the heart of the Latin Quarter",
  name: "Le Panthéon",
  address: "Le Panthéon, place du Panthéon, 75005 Paris",
  photo:"https://www.parisinfo.com/var/otcp/sites/images/media/1.-photos/02.-sites-culturels-630-x-405/pantheon-vue-generale-630x405-c-thinkstock/36266-1-fre-FR/Pantheon-vue-generale-630x405-C-Thinkstock.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  sight_seeing_adventurer: true,
  budget: 1,
  knows_the_city: 3,
  website: "http://www.paris-pantheon.fr/",
},
{
  title:"Visit of the Grand Palais",
  name: "Le Grand Palais",
  address: "3 Avenue du Général Eisenhower, 75008 Paris",
  photo:"https://www.parisinfo.com/var/otcp/sites/images/media/1.-photos/02.-sites-culturels-630-x-405/le-grand-palais-630x405-c-otcp-david-lefranc-i-155-12/26729-1-fre-FR/Le-Grand-Palais-630x405-C-OTCP-David-Lefranc-I-155-12.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  sight_seeing_adventurer: true,
  budget: 3,
  knows_the_city: 2,
  website: "http://www.grandpalais.fr/",
},
{
  title:"Visit of the Basilique du Sacré-coeur and Montmartre neighborhood",
  name: "Montmartre et le Sacré-Coeur",
  address: "35 rue du Chevalier de la Barre, 75018 Paris",
  photo:"https://www.france-hotel-guide.com/fr/blog/wp-content/uploads/2014/10/Sacré-Coeur-pixabay.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  sight_seeing_adventurer: true,
  budget: 3,
  knows_the_city: 2,
  website: "http://www.sacre-coeur-montmartre.com/",
},
{
  title:"Visit of Rodin's museum and walk around the Invalides",
  name: "Musée Rodin",
  address: "77 Rue de Varenne, 75007 Paris",
  photo:"https://www.parisinfo.com/var/otcp/sites/images/media/1.-photos/02.-sites-culturels-630-x-405/musee-rodin-parc-630x405-c-otcp-jacques-lebar-i-162-37/25445-1-fre-FR/Musee-Rodin-parc-630x405-C-OTCP-Jacques-Lebar-I-162-37.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  sight_seeing_adventurer: true,
  budget: 2,
  knows_the_city: 3,
  website: "http://www.musee-rodin.fr/",
},
{
  title:"Bateaux Mouches trip on the Seine",
  name: "Bateaux Mouches",
  address: "Port de la Conférence, 75008 Paris",
  photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Bateau-Mouche-Galere.jpg/1200px-Bateau-Mouche-Galere.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  sight_seeing_adventurer: true,
  budget: 2,
  knows_the_city: 3,
  website: "http://www.bateaux-mouches.fr/",
},
{
  title:"Discovery of the Louis Vuitton Fundation next to the Bois de Boulogne",
  name: "Fondation Louis Vuitton",
  address: "77 Rue de Varenne, 75007 Paris",
  photo:"http://www.fondationlouisvuitton.fr/content/flvinternet/fr/Galleries/menu/jcr:content/content/image_22fd.flvcrop.768.5000.jpeg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  sight_seeing_adventurer: true,
  budget: 3,
  knows_the_city: 3,
  website: "http://www.fondationlouisvuitton.fr/",
},
{
  title:"Visit of the Opera Garnier",
  name: "Opera Garnier",
  address: "8 Rue Scribe, 75009 Paris",
  photo:"https://cdn.pariscityvision.com/media/catalog/product/cache/2/image/755x433/9df78eab33525d08d6e5fb8d27136e95/O/p/Opera-Garnier-un-chef-d-oeuvre-architectural-589207b69298a.jpeg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  sight_seeing_adventurer: true,
  budget: 2,
  knows_the_city: 2,
  website: "https://www.operadeparis.fr/",
},
{
  title:"Stroll through the Pere Lachaise Cemetery",
  name: "Pere Lachaise Cemetery",
  address: "16 Rue du Repos, 75020 Paris",
  photo:"http://pariseastvillage.com/wp-content/uploads/2016/02/cimetiere-pere-lachaise-paris-east-village-2.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  sight_seeing_adventurer: true,
  budget: 1,
  knows_the_city: 3,
  website: "https://www.parisinfo.com/musee-monument-paris/71470/Cimetiere-du-Pere-Lachaise",
},
{
  title:"Visit of the beautiful Musée d'Orsay",
  name: "Musée d'Orsay",
  address: "1 Rue de la Légion d'Honneur, 75007 Paris",
  photo:"https://pbs.twimg.com/media/DQhscjgXkAAhGb3.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  sight_seeing_adventurer: true,
  budget: 3,
  knows_the_city: 3,
  website: "http://www.musee-orsay.fr/",
},
{
  title:"Discover the charming and discreet Place Fürstenberg",
  name: "Place Fürstenberg",
  address: "1 Rue de la Légion d'Honneur, 75007 Paris",
  photo:"http://www.parisaddress.com/var/thumbs/items/other/975x450_0b545108904765462ff3256cf3cbc3bd80.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  city_wanderer: true,
  budget: 1,
  knows_the_city: 3,
  website: "http://www.musee-delacroix.fr/fr/le-musee/atelier-au-musee/la-place-de-furstenberg",
},
{
  title:"Stroll through the Rue Cremieux",
  name: "Rue Cremieux - 12th District",
  address: "Rue Crémieux, 75012 Paris",
  photo:"http://www.pariszigzag.fr/wp-content/uploads/2016/08/Rue-cre%CC%81mieux-GD4.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  city_wanderer: true,
  budget: 1,
  knows_the_city: 4,
},
{
  title:"Journey at the Coulée Verte",
  name: "Coulée verte René-Dumont",
  address: "1 Coulée verte René-Dumont, 75012 Paris",
  photo:"https://media.timeout.com/images/100013521/image.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  city_wanderer: true,
  budget: 1,
  knows_the_city: 3,
  website: "http://equipement.paris.fr/coulee-verte-rene-dumont-ex-promenade-plantee-1772#local-calendar",
},

{
  title:"Visit of the Passage des Panoramas",
  name: "Passage des Panoramas",
  address: "11 Boulevard Montmartre, 75002 Paris",
  photo:"https://www.parisinfo.com/var/otcp/sites/images/media/1.-photos/80.-photos-sugar/lieux-de-loisirs-et-de-culture/passage-des-panoramas-%7C-630x405-%7C-%C2%A9-otcp-marc-bertrand/10653601-1-fre-FR/Passage-des-Panoramas-%7C-630x405-%7C-%C2%A9-OTCP-Marc-Bertrand.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  city_wanderer: true,
  budget: 1,
  knows_the_city: 3,
  website: "https://www.parisinfo.com/musee-monument-paris/100264/Passage-des-Panoramas",
},
{
  title:"A step in India at the heart of Paris",
  name: "Passage Brady",
  address: "46 rue du Faubourg Saint-Denis, 75010 Paris",
  photo:"http://www.visitparisregion.com/fichiers/fckeditor/Image/58/fr/original/passage-brady-paris.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  city_wanderer: true,
  budget: 1,
  knows_the_city: 4,
  website: "https://www.parisinfo.com/musee-monument-paris/100266/Passage-Brady",
},
{
  title:"Long walk on the rails",
  name: "La Petite Ceinture",
  address: "36 boulevard de Beauséjour, 75016 Paris",
  photo:"http://www.guideparisci.com/wp-content/uploads/2015/04/petite-ceinture.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  city_wanderer: true,
  budget: 1,
  knows_the_city: 4,
  website: "https://www.parisinfo.com/musee-monument-paris/71366/La-petite-ceinture",
},
{
  title:"Break from the city at the heart of Paris",
  name: "Place Dauphine",
  address: "Place Dauphine, 75001 Paris",
  photo:"http://ncfor.com/images/maison-et-objet-dates-3-25-place-dauphine-paris-perfect-1920x1080.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  city_wanderer: true,
  budget: 1,
  knows_the_city: 3,
  website: "https://www.parisinfo.com/transports/73133/Place-Dauphine",
},
{
  title:"Discover the artwork of Buren's Columns",
  name: "Les deux plateaux de Buren",
  address: "2 Rue de Montpensier, 75001 Paris",
  photo:"http://www.pariszigzag.fr/wp-content/uploads/2016/05/Fontaine-souterraine-750x491.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  city_wanderer: true,
  budget: 1,
  knows_the_city: 2,
  website: "https://danielburen.com/",
},
{
  title:"Enjoy the nature at the Quartier Mouzaïa",
  name: "Quartier Mouzaïa",
  address: "Rue Mouzaïa, 75019 Paris",
  photo:"https://4.bp.blogspot.com/-bPpoX4ZNQ0c/WPDYGD-BkLI/AAAAAAAAsOA/s17BgbcwECgyJUMGUcSCHqtZo7ct64LQgCLcB/s1600/mouzaia-quartier-paris-19-13.JPG",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  city_wanderer: true,
  budget: 1,
  knows_the_city: 4,
},
{
  title:"Chill at les Arènes de Lutèce",
  name: "Les Arènes de Lutèce",
  address: "49 Rue Monge, 75005 Paris",
  photo:"https://www.parisinfo.com/var/otcp/sites/images/media/1.-photos/02.-sites-culturels-630-x-405/arenes-de-lutece-630x405-c-otcp-marc-bertrand-i-153-05/28062-1-fre-FR/Arenes-de-Lutece-630x405-C-OTCP-Marc-Bertrand-I-153-05.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  city_wanderer: true,
  budget: 1,
  knows_the_city: 4,
  website: "https://www.parisinfo.com/musee-monument-paris/71451/Ar%C3%A8nes-de-Lut%C3%A8ce",
},
{
  title:"Visit of the Army Museum at les Invalides",
  name: "Hôtel National des Invalides",
  address: "Place des Invalides, 75007 Paris",
  photo:"http://www.freemages.com/album/paris/cour_des_invalides.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  history_passionate: true,
  budget: 1,
  knows_the_city: 2,
  website: "http://www.musee-armee.fr/lhotel-des-invalides.html",
},
{
  title:"Visit of the Pablo Picasso Museum",
  name: "Musée National Picasso Paris",
  address: "5 Rue de Thorigny, 75003 Paris",
  photo:"https://www.google.fr/search?q=pablo+picasso+mus%C3%A9e&rlz=1C5CHFA_enFR762FR762&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiogLD6jYLYAhUoLsAKHSinAcQQ_AUICigB&biw=1280&bih=680#imgdii=2GE_pJHHDLV7tM:&imgrc=yD1PVCJcjGgoXM:",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  history_passionate: true,
  budget: 1,
  knows_the_city: 3,
  website: "http://www.museepicassoparis.fr/",
},
{
  title:"Discovery of impressionism at the Musée de l'Orangerie",
  name: "Musée de l'Orangerie",
  address: "Jardin Tuileries, 75001 Paris",
  photo:"https://intothegallerydotcom.files.wordpress.com/2016/04/ra-monet-orangerie.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  history_passionate: true,
  budget: 2,
  knows_the_city: 2,
  website: "http://www.musee-orangerie.fr/",
},
{
  title:"Admire the Sainte Chapelle",
  name: "Sainte Chapelle du Palais",
  address: "8 Boulevard du Palais, 75001 Paris",
  photo:"http://www.parismuseumpass.com/datas/musees/s/a/sainte-chapelle/xl/sainte-chapelle-4cd2e0815f2d7.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  history_passionate: true,
  budget: 3,
  knows_the_city: 2,
  website: "http://www.sainte-chapelle.fr/",
},
{
  title:"Visit the museum of art and history of judaism",
  name: "Musée d'Art et d'Histoire du Judaïsme",
  address: "Hôtel de Saint-Aignan, 71 Rue du Temple, 75003 Paris",
  photo:"https://www.mahj.org/sites/mahj.org/files/styles/diaporama/public/thumbnails/image/_dsc2106.jpg?itok=2qPbCOK7",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  history_passionate: true,
  budget: 2,
  knows_the_city: 4,
  website: "https://www.mahj.org/fr",
},
{
  title:"Visit the Musée de l'Homme at Trocadero",
  name: "Musée de l'Homme",
  address: "17 Place du Trocadéro et du 11 Novembre, 75116 Paris",
  photo:"https://www.proxifun.com/wp-content/uploads/2016/11/musee-histoire-naturelle-paris-2.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  history_passionate: true,
  budget: 2,
  knows_the_city: 2,
  website: "http://www.museedelhomme.fr/",
},
{
  title:"Discover the Cernuschi Museum",
  name: "Musée Cernuschi",
  address: "7 avenue Vélasquez, 75008 Paris",
  photo:"http://www.cernuschi.paris.fr/sites/cernuschi/files/styles/home_img_fond/public/cernuschi-visuel-home_110405_0.jpg?itok=d7SjcNcn",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  history_passionate: true,
  budget: 1,
  knows_the_city: 2,
  website: "http://www.cernuschi.paris.fr/",
},
{
  title:"Visit the Jacquemart André Museum",
  name: "Musée Jacquemart André",
  address: "158 Boulevard Haussmann, 75008 Paris",
  photo:"https://www.parisinfo.com/var/otcp/sites/images/media/1.-photos/80.-photos-sugar/lieux-de-loisirs-et-de-culture/musee-jacquemart-andre-5-630x405-c-sofiacom/5047524-1-fre-FR/Musee-Jacquemart-Andre-5-630x405-C-Sofiacom.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  history_passionate: true,
  budget: 1,
  knows_the_city: 2,
  website: "http://musee-jacquemart-andre.com/",
},
{
  title:"Visit at the Musée des Archives Nationales",
  name: "Musée des Archives Nationales",
  address: "60 Rue des Francs Bourgeois, 75003 Paris",
  photo:"https://www.lagoradesarts.fr/IMG/jpg/ParisOK.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  history_passionate: true,
  budget: 1,
  knows_the_city: 4,
  website: "http://www.archives-nationales.culture.gouv.fr/",
},
{
  title:"Visit the famous writer Victor Hugo's house",
  name: "Maion de Victor Hugo",
  address: "6 place des Vosges, Paris, 75004",
  photo:"http://www.marche-poesie.com/wp-content/uploads/2017/04/Maison-Victor-Hugo.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  history_passionate: true,
  budget: 1,
  knows_the_city: 4,
  website: "http://www.maisonsvictorhugo.paris.fr/",
},
{
  title:"Discover the Chinese Culture",
  name: "Les Temps du Corps",
  address: "10 Rue de l'Échiquier, 75010 Paris",
  photo:"http://www.ke-wen.fr/wp-content/uploads/2014/12/beidaihe-8.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  relaxed: true,
  budget: 3,
  knows_the_city: 3,
  website: "http://www.tempsducorps.org/",
},
{
  title:"Get a wonderful massage at the Mandarin Hotel",
  name: "Spa, Hôtel Mandarin",
  address: "251 Rue Saint Honoré, 75001 Paris",
  photo:"https://i.pinimg.com/originals/37/14/57/371457c86a149f09086d978809dd7042.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  relaxed: true,
  budget: 5,
  knows_the_city: 3,
  website: "http://www.mandarinoriental.fr/paris/luxury-spa/",
},
{
  title:"Start doing meditation",
  name: "Ecole Occidentale de la méditation",
  address: "53 Rue Raymond Losserand, 75014 Paris",
  photo:"https://www.ecole-occidentale-meditation.com/wp-content/uploads/2017/06/BD_La-Prudentielle-Apres-495x400.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  relaxed: true,
  budget: 2,
  knows_the_city: 3,
  website: "https://www.ecole-occidentale-meditation.com/",
},
{
  title:"Learn Garuda and get relaxed",
  name: "Tchilo Body Lab",
  address: "9 Rue Charles-François Dupuis, 75003 Paris",
  photo:"https://i.pinimg.com/originals/37/14/57/371457c86a149f09086d978809dd7042.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  relaxed: true,
  budget: 4,
  knows_the_city: 3,
  website: "http://www.tchilo.com/",
},
{
  title:"Practice urban Ashram",
  name: "Sivanda",
  address: "140 rue du Faubourd-Saint-Martin, 75010 Paris",
  photo:"http://www.sivananda.org/paris/images/favicons/og_image_ALR5704.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  relaxed: true,
  budget: 3,
  knows_the_city: 3,
  website: "http://www.sivananda.org/paris/",
},
{
  title:"Get relaxed at the Nuxe Spa",
  name: "Spa Nuxe",
  address: "32-34 Rue Montorgueil, 75001 Paris",
  photo:"https://nuxe.cdn.oxv.fr/var/images/1404395628--jmp5316-cmjn.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  relaxed: true,
  budget: 5,
  knows_the_city: 3,
  website: "https://fr.nuxe.com/nuxe-spa",
},
{
  title:"Workshop on plantar reflexology",
  name: "Le Hasard Ludique",
  address: "128 avenue de Saint Ouen, 75018 Paris",
  photo:"https://www.massage-bien-etre-angers.fr/wp-content/uploads/2015/11/r%C3%A9flexologie-plantaire-1.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  relaxed: true,
  budget: 3,
  knows_the_city: 3,
  website: "https://www.lehasardludique.paris/prends-soin-de-toi/decouverte-de-la-reflexologie-plantaire",
},
{
  title:"Workshop on well-being",
  name: "Le Hasard Ludique",
  address: "128 avenue de Saint Ouen, 75018 Paris",
  photo:"https://www.studiomonceau.com/wp-content/uploads/2016/10/d%C3%A9veloppement-personnel-1.png",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  relaxed: true,
  budget: 3,
  knows_the_city: 3,
  website: "https://www.lehasardludique.paris/prends-soin-de-toi/liberez-votre-super-vous",
},
{
  title:"Discover the practice of Hatha Yoga",
  name: "Yoga Hatha lesson",
  address: "7 Rue de Plaisance, 75014 Paris",
  photo:"http://i0.wp.com/yogamanjali.com/wp-content/uploads/2015/06/Stage-yoga-01-yogamanjali-Paris-20.jpg?resize=1080%2C675",
  solo: true,
  couple: true,
  friends: true,
  to_book: true,
  relaxed: true,
  budget: 3,
  knows_the_city: 3,
  website: "http://ffhy.ff-hatha-yoga.com/",
},
{
  title:"Traditional Thai Chi",
  name: "Thai Chi Lesson",
  address: "9 Rue Alphonse Baudin, 75011 Paris",
  photo:"http://www.quatrepiliers.fr/wordpress/wp-content/uploads/2017/05/slider-tai-chi-1768x822.jpg",
  solo: true,
  couple: true,
  friends: true,
  to_book: false,
  relaxed: true,
  budget: 3,
  knows_the_city: 3,
  website: "http://centre.taichichuan.free.fr/",
},
]
Activity.create(activities_attributes)

fin = Time.now
puts "Finished seeding in #{(fin - start).round(2)} seconds!"



